In [1]:
!pip3 install numpy

  Using cached https://files.pythonhosted.org/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for numpy: filename=numpy-1.19.5-cp38-cp38-macosx_10_14_6_x86_64.whl size=6395081 sha256=801a624ff8cc2126c3ad1e614ef9b21f3e2a19b31e13a184a41dc0496b903756
  Stored in directory: /Users/jungseong/Library/Caches/pip/wheels/ee/cd/78/686734467766f26e3d2b42605dce9fdb7d24c1c1d26f2fb8fc
Successfully built numpy
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.

You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np

In [5]:
a= np.array([[10, 8], [3, 5]])

In [6]:
b=np.linalg.inv(a)

In [8]:
a@b

array([[1., 0.],
       [0., 1.]])

In [9]:
np.linalg.eig(a)

(array([13.,  2.]),
 array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [10]:
np.linalg.svd(a)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))